import React, { useState, useEffect } from "react";
import { Typography, Container } from "@mui/material";
import RandomImageDisplay from "../../constants/RandomImageDisplay";
import { RecordView } from "./StudyRound";
import { appConfig } from "../../constants/config";

export const SelectImagePage = (props) => {
  const [selectedImage, setSelectedImage] = useState(null);
  const [images, setImages] = useState([]);          // shown images
  const [roundData, setRoundData] = useState(null);  // full logging packet

  useEffect(() => {
    fetch("/api/images?domain=landscapes")
      .then((r) => r.json())
      .then((data) => {
        const total = 5; // 1 human + 4 AI

        const human = Array.isArray(data.human) ? data.human : [];
        const models = data.models || {};

        const humanPick =
          human[Math.floor(Math.random() * human.length)];

        const allAi = Object.entries(models).flatMap(
          ([modelName, urls]) => urls.map((src) => ({ src, modelName }))
        );

        const aiPicks = allAi.sort(() => Math.random() - 0.5).slice(0, 4);

        const merged = [
          { src: humanPick, type: "image", label: "human" },
          ...aiPicks.map(({ src, modelName }) => ({
            src,
            type: "image",
            label: "ai",
            model: modelName,
          })),
        ].sort(() => Math.random() - 0.5);

        setImages(merged);
      });
  }, []);

  const handleSelect = (img) => {
    setSelectedImage(img);

    const anonId = localStorage.getItem("anonId") || "unknown";

    // build unified round log
    const dataPacket = {
      anonId,
      studyType: "landscapes",
      round: 1, // we will update later when doing multipage
      shown: images.map((i) => ({
        src: i.src,
        label: i.label,
        model: i.model || null,
      })),
      selected: {
        src: img.src,
        label: img.label,
        model: img.model || null,
      },
      correctGuess: img.label === "ai", // user picks the one they *think* is AI
      timestamp: Date.now(),
    };

    setRoundData(dataPacket);

    // send once
    fetch("/api/logRound", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(dataPacket),
    }).catch(console.error);
  };

  return (
    <Container maxWidth="md" style={{ textAlign: "center", marginTop: 30 }}>
      <Typography variant="h3" gutterBottom>
        Which Image Do You Think Is AI?
      </Typography>

      {!selectedImage ? (
        <>
          <Typography variant="subtitle1" color="textSecondary">
            Click on the image you believe was generated by AI.
          </Typography>

          {images.length > 0 && (
            <RandomImageDisplay
              images={images}
              numImages={images.length}
              onSelect={handleSelect}
              selectedMedia={selectedImage}
            />
          )}
        </>
      ) : (
        <>
          <Typography variant="h6">You selected:</Typography>
          <img
            src={selectedImage.src}
            alt="Selected"
            style={{ width: 500, borderRadius: 8, marginTop: 10 }}
          />

          <RecordView
            idx={0}
            theme={{ name: "landscape_ai_guess" }}
            screenIdx={0}
            contentType="image"
            last={true}
            state={props.state}
            feedbackMode={appConfig.feedbackMode}
            mediaData={selectedImage}
          />
        </>
      )}
    </Container>
  );
};

export default SelectImagePage;
